### ISSUE TITLE
Module not found "mido"

### ISSUE THREAD

**Issue by rylid-umil** [thatsOven/ArrayVMusicTool#1]
`Traceback (most recent call last):
  File "C:\Users\[hide]l\Downloads\ArrayVMusicTool-main\ArrayVMusicTool-main\ArrayVMusicTool.py", line 25, in <module>
    from mido import MidiFile
ModuleNotFoundError: No module named 'mido'` 
it doesnt even

**Comment by thatsOven** [comment]
documentation has been updated to indicate that the mido module needs to be installed

**Comment by thatsOven** [comment]
documentation has been updated to indicate that the mido module needs to be installed
